# Generated by Django 5.2.13 on 2026-04-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('servico_realizado', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Aguardando', max_length=20)),
                ('data_entrada', models.CharField(max_length=20)),
                ('data_previsao', models.CharField(blank=True, max_length=20, null=True)),
                ('data_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='core.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='core.veiculo')),
            ],
        ),
    ]
